### ISSUE TITLE
modules/encoders/cipher/bitwise_xor: Stack level too deep error

### ISSUE THREAD

**Issue by cliffe** [cliffe/SecGen#158]
```
ruby modules/encoders/cipher/bitwise_xor/secgen_local/local.rb --b64 --strings_to_encode=MTAyMTA4MDk3MTAzMTIzMDk5MTAwMTAwMTAwMTAwMDU3MDUxMDUxMTI1
Bitwise XOR Challenge Generator
Reading args from STDIN
 Encoding '["102108097103123099100100100100057051051125"]'
 Encoded: ["010101100111010001111000011101010110011110100000110101100001000000001000110110011000110100111010100001100000010111010111110011101111110110100000111000100101100100001011011010011111101111111011000100000011011010000010001001011110010101001100101010010110100111111001101000010000101001110001100111011010111011111100011011111001100100001110_011001110100010001001010010001000101011110011000111001100010100100111111111010001011110100001001101101110011011111100100111111101100010010011001110100110110100100111011010110001100101111001011001000010000011010110010000101001101010101111100100110010101110011001110100100010011111101000000101011011001101111001101010111101010101100111011", [...]]...
/home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `map': stack level too deep (SystemStackError)
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `array_to_utf8'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:32:in `block in array_to_utf8'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `map'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `array_to_utf8'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:32:in `block in array_to_utf8'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `map'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:26:in `array_to_utf8'
        from /home/secgen/SecGen/lib/objects/local_encoding_functions.rb:32:in `block in array_to_utf8'
         ... 11220 levels...
        from /home/secgen/SecGen/lib/objects/local_string_encoder.rb:141:in `each'
        from /home/secgen/SecGen/lib/objects/local_string_encoder.rb:141:in `enforce_utf8'
        from /home/secgen/SecGen/lib/objects/local_string_encoder.rb:135:in `run'
        from modules/encoders/cipher/bitwise_xor/secgen_local/local.rb:45:in `<main>'
```

**Comment by cliffe** [comment]
In the meantime, I'll set it to conflict with everything, so it doesn't get selected into scenarios.

**Comment by cliffe** [comment]
Todo: remove the module permanently (won't fix)
