### ISSUE TITLE
New project using Ovirt 4 provider fails

### ISSUE THREAD

**Issue by jeremytourville** [cliffe/SecGen#160]
I have built a new Ubuntu 18.04 server to run SecGen this week.  My virtualization platform is Ovirt and so I am using the Ovirt provider. I also exported a system variable `export VAGRANT_DEFAULT_PROVIDER=ovirt`.  I am running the following to start the process:

 ` ruby secgen.rb --ovirtuser admin@internal --ovirtpass my_pass --ovirt-url engine.cyber-range.lan/ovirt-engine --ovirt-cluster Default --ovirt-network Client run`.

The project appears to get fairly far creating a build and then stops.  Here is the last section before failure, I can provide more if needed.

```
Loading vagrant (up ) in /home/user/bin/SecGen/SecGen-master/projects/SecGen20191207_1303
Bringing machine 'escalation' up with 'virtualbox' provider...
==> escalation: Box 'ovirt4' could not be found. Attempting to find and install...
    escalation: Box Provider: virtualbox
    escalation: Box Version: >= 0
==> escalation: Box file was not detected as metadata. Adding it directly...
==> escalation: Adding box 'ovirt4' (v0) for provider: virtualbox
    escalation: Downloading: https://github.com/myoung34/vagrant-ovirt4/blob/master/example_box/dummy.box?raw=true
    escalation: Progress: 0Error provisioning VMs, destroying VMs and exiting SecGen.
Loading vagrant (destroy -f) in /home/user/bin/SecGen/SecGen-master/projects/SecGen20191207_1303
==> escalation: VM not created. Moving on...
```

I reviewed the ouput of the vagrantfile.  I made sure my templates in Ovirt matched the name of the template specified in the Vagrantfile.  If I go into the project directory and run `vagrant up` I get the following: 

```
user@localhost:~/bin/SecGen/SecGen-master/projects/SecGen20191207_1303$ vagrant up
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:1059:in `chmod': Operation not permitted @ chmod_internal - /home/user/.vagrant.d/insecure_private_key (Errno::EPERM)
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:1059:in `chmod'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:1059:in `copy_insecure_private_key'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:166:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:145:in `new'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:145:in `<main>'
```

**Comment by jeremytourville** [comment]
After further review, I realized I had several permissions issues.  I corrected them.  At this point vagrant up reports a different error.  
```

`user@secgen2:~/bin/SecGen/projects/SecGen20191207_160006$ vagrant up
/home/user/.vagrant.d/gems/2.4.9/gems/vagrant-ovirt-0.0.2/lib/vagrant-ovirt.rb:44:in `default_provider': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/up/command.rb:87:in `execute'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
user@secgen2:~/bin/SecGen/projects/SecGen20191207_160006$ cd ~/
`
```

**Comment by jeremytourville** [comment]
Ok, some further testing confirms that there is some sort of Vagrant issue.  I'm going to raise the issue in the Vagrant Github and see what they can figure out.  No reply is needed at this point.  I'll reply back here with my findings so everyone can benefit.

**Comment by jeremytourville** [comment]
After further testing the issue is clearly vagrant & ovirt related.  No issues with this project. so I'm closing this issue.

**Comment by cliffe** [comment]
Hi @jeremytourville. Good luck!
