### ISSUE TITLE
Scenario ctf/basic_narrative fails to complete build

### ISSUE THREAD

**Issue by jeremytourville** [cliffe/SecGen#161]
I am using Ovirt4 plugin.  The build gets pretty far along and then fails.

```
==> target_server: Running Puppet with environment production...
==> target_server: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> target_server:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/apache/manifests/init.pp", 133]:["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/onlinestore/manifests/init.pp", 2]
==> target_server: (at /tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/apache/manifests/init.pp", 342]:["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/onlinestore/manifests/init.pp", 2]
==> target_server:    (at /tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/apache/manifests/mod/negotiation.pp", 9]:["/tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/apache/manifests/default_mods.pp", 133]
==> target_server:    (at /tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Error: Syntax error at '=>' at /tmp/vagrant-puppet/modules-b05583e08b62f5aa0d968a6e2c877ad4/onlinestore/manifests/install.pp:20:31 on node secgen-basic-narrative-target-server.cyber-range.lan
==> target_server: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'target_server'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

An error occurred while executing the action on the 'attack_vm'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Non-zero exit status...
Error provisioning VMs, destroying VMs and exiting SecGen.
Loading vagrant (destroy -f) in /home/user/bin/SecGen/projects/SecGen20200111_022412
==> attack_vm: Halting VM...
==> attack_vm: Waiting for VM to shutdown...
==> attack_vm: Removing VM...
==> target_server: Halting VM...
==> target_server: Waiting for VM to shutdown...
==> target_server: Removing VM...

```
Any thought on this?

**Comment by jeremytourville** [comment]
I was able to get this scenario to work using VirtualBox provider.  No issues with scenario or base boxes.  I will raise a separate query about oVirt specifics.
