### ISSUE TITLE
Scenario ctf/basic_narrative fails to build in oVirt but works in VirtualBox

### ISSUE THREAD

**Issue by jeremytourville** [cliffe/SecGen#167]
I have configured an Ovirt template with vagrant.  The build fails part way through and does not finish.  Can anyone suggest where to start troubleshooting?

```
==> target_server: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> target_server:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/apache/manifests/init.pp", 133]:["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/onlinestore/manifests/init.pp", 2]
==> target_server:    (at /tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/apache/manifests/init.pp", 342]:["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/onlinestore/manifests/init.pp", 2]
==> target_server:    (at /tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/apache/manifests/mod/negotiation.pp", 9]:["/tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/apache/manifests/default_mods.pp", 133]
==> target_server:    (at /tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> target_server: Error: Syntax error at '=>' at /tmp/vagrant-puppet/modules-7120f19ad726819ebc7ad97a6be0685f/onlinestore/manifests/install.pp:20:31 on node secgen-basic-narrative-target-server.cyber-range.lan
==> target_server: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'target_server'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

An error occurred while executing the action on the 'attack_vm'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by cliffe** [comment]
Guessing it might be the version of puppet installed.

**Comment by cliffe** [comment]
Oh, see https://github.com/cliffe/SecGen/pull/166/commits/87e7dc8d2e34c80a56cd04e6bf54dc5335129a84

**Comment by cliffe** [comment]
That fix is merged now. Not sure but I guess some versions of puppet interpret => as >= depending on context.

**Comment by jeremytourville** [comment]
Ok, I'll update SecGen on my machine and try to run the scenario again.  More to follow....  Thanks!

**Comment by jeremytourville** [comment]
I think the scenario built for the target machine but failed for the attack vm.  Can you confirm?  I believe the scenario fails on the attack vm for an issue with iceweasel.  My oVirt kali template is based on 2019.3  x64 bit.

```
==> attack_vm: Error: /Stage[main]/Iceweasel::Install/Package[iceweasel]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install iceweasel' returned 100: Reading package lists...
==> attack_vm: Building dependency tree...
==> attack_vm: Reading state information...
==> attack_vm: Package iceweasel is not available, but is referred to by another package.
==> attack_vm: This may mean that the package is missing, has been obsoleted, or
==> attack_vm: is only available from another source
==> attack_vm:
==> attack_vm: E: Package 'iceweasel' has no installation candidate
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/]/ensure: created
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/firefox]/ensure: created
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/firefox/user.default]/ensure: created
==> target_server: Running provisioner: shell...
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/firefox/profiles.ini]/ensure: defined content as '{md5}83d2811615a024817ee5388bd7b5c76a'
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/firefox/installs.ini]/ensure: defined content as '{md5}0302ead8c840e48d8f2244fa8a3c71b2'
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.mozilla/firefox/user.default/user.js]/ensure: defined content as '{md5}81cec6b90d2dbc9c711e1229a1d2adde'
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.config/autostart/]/ensure: created
==> attack_vm: Notice: /Stage[main]/Iceweasel::Config/File[/root/.config/autostart/iceweasel.desktop]/ensure: defined content as '{md5}1d70e6f900e67c82b84056e8a412af94'
==> attack_vm: Notice: Applied catalog in 0.70 seconds
==> attack_vm: An error occurred. The error will be shown after all tasks complete.


==> target_server: Notice: Compiled catalog for secgen-basic-narrative-target-server.cyber-range.lan in environment production in 0.21 seconds
==> target_server: Notice: /Stage[main]/Cleanup::Init/Exec[remove_history]/returns: executed successfully
==> target_server: Notice: /Stage[main]/Cleanup::Init/Accounts::User[root]/User[root]/password: changed password
==> target_server: Notice: /Stage[main]/Cleanup::Init/Accounts::User[root]/Accounts::Home_dir[/root]/File[/root/.ssh]/ensure: created
==> target_server: Notice: /Stage[main]/Cleanup::Init/Accounts::User[root]/Accounts::Home_dir[/root]/File[/root/.vim]/ensure: created
==> target_server: Notice: /Stage[main]/Cleanup::Init/Accounts::User[root]/Accounts::Home_dir[/root]/File[/root/.ssh/authorized_keys]/ensure: created
==> target_server: Notice: Applied catalog in 0.23 seconds
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'attack_vm'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
